#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "mcp-vtex"
main = "server/main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "deco-team"

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[deco]
workspace = "deco-team"
enable_workflows = false
local = false

[deco.integration]
friendlyName = "VTEX [New]"
icon = "https://assets.decocache.com/mcp/0d6e795b-cefd-4853-9a51-93b346c52c3f/VTEX.svg"